### PR TITLE
Fix missing error context in error collection crashing sqlparse

### LINKED ISSUE #66: Missing closing bracket leads to crash of js sql-parse
Example:
```sql
CREATE TABLE t01 (
   "x" OBJECT (DYNAMIC),
   "y" OBJECT (DYNAMIC) AS ("z" ARRAY(OBJECT (DYNAMIC))      
   );
```

Leads to:
```
file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:85514
      e2.ctx.parser.getTokenStream().getText(
         ^

TypeError: Cannot read properties of null (reading 'ctx')
    at ExceptionCollectorListener.syntaxError (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:85514:10)
    at file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:1647:37
    at Array.map (<anonymous>)
    at Rt.syntaxError (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:1647:22)
    at _SqlBaseParser.notifyErrorListeners (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:3569:39)
    at Ae.reportUnwantedToken (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:3136:10)
    at Ae.sync (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:3109:16)
    at _SqlBaseParser.createStmt (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:67301:30)
    at _SqlBaseParser.statement (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:60659:16)
    at _SqlBaseParser.statements (file:///Users/georg/sqlparsetest/node_modules/@cratedb/cratedb-sqlparse/dist/sqlparse.js:58435:12)
```

### PR DESCRIPTION
**Pull request by surister**
## Summary of the changes / Why this is an improvement
Fixes #66 

## Checklist

 - [x] Link to issue this PR refers to (if applicable): Fixes #???

### CODE REVIEW

File: cratedb_sqlparse_js/cratedb_sqlparse/parser.js [hunk 1]
```diff
@@ -124,11 +124,23 @@ class ExceptionCollectorListener extends ErrorListener {
...
+        if (e !== null) {
+            query = e.ctx.parser.getTokenStream().getText(new Interval(
                 e.ctx.start,
                 e.offendingToken.tokenIndex)
-            ),
+            )
+
+        } else {
+
+            let min_to_check = Math.max(1, offendingSymbol.tokenIndex - 2)
```
Comment (kneth) [inline cratedb_sqlparse_js/cratedb_sqlparse/parser.js:137]: I suggest that you use `const` instead of `let`

File: cratedb_sqlparse_js/cratedb_sqlparse/parser.js [hunk 2]
```diff
@@ -124,11 +124,23 @@ class ExceptionCollectorListener extends ErrorListener {
...
+            let tokens = recognizer.getTokenStream().tokens.slice(min_to_check, offendingSymbol.tokenIndex + 1)
```
Comment (kneth) [inline cratedb_sqlparse_js/cratedb_sqlparse/parser.js:138]: Same as above

File: cratedb_sqlparse_js/cratedb_sqlparse/parser.js [hunk 3]
```diff
@@ -124,11 +124,23 @@ class ExceptionCollectorListener extends ErrorListener {
 
     syntaxError(recognizer, offendingSymbol, line, column, msg, e) {
         super.syntaxError(recognizer, offendingSymbol, line, column, msg, e);
-        const error = new ParseError(
-            e.ctx.parser.getTokenStream().getText(new Interval(
+        let query;
+
+        if (e !== null) {
```
Comment (kneth) [inline cratedb_sqlparse_js/cratedb_sqlparse/parser.js:129]: I think it will be more readable if you use `if (e) { ...` and swap the two branches. And it will be similar to the Python code.

**Review by kneth — APPROVED** [review]
My comments are suggestions, and they are no way blocking you from merging 😄

**Comment by surister** [comment]
Fixed dependency missmatches (dependabot Prs were merged earlier) and applied comments. Thanks!
